server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://scotty.ink:3306/cdd?useUnicode=true&&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  #  mapper-locations: classpath:mapper/*.xml
  #  config-location: classpath:mybatis-config.xml
  type-aliases-package: ink.scotty.cdd